# Generated by Django 4.1 on 2022-09-13 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aegc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
