# Generated by Django 4.1 on 2022-09-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegc', '0002_carousel_name_carousel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
