# Generated by Django 4.1 on 2022-09-13 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aegc', '0005_alter_carousel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
