# Generated by Django 4.1 on 2022-09-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegc', '0007_remove_carousel_date_alter_carousel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='uploads/Visa')),
                ('location', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
