# Generated by Django 4.1 on 2022-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegc', '0008_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
