# Generated by Django 4.1 on 2022-11-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegc', '0010_social_rename_name_carousel_title_carousel_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/Team'),
        ),
    ]
