# Generated by Django 4.1 on 2022-11-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aegc', '0011_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='field',
            new_name='qualification',
        ),
    ]
